### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by evamcconville** [SchoolOfCode/escape-room-hackathon-abhiling#4]
```[tasklist]
### Tasks
- [x] create a new Postgres database
- [x] rename .env example
- [x] add `DB_CONNECTION_STRING` from render
- [x] add port
- [x] npm install
- [x] npm run dev
- [x] heck contection to database
```
